apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
    - 172.28.128.245-172.28.128.254

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: libvirt-l2
  namespace: metallb
spec:
  ipAddressPools:
    - first-pool
